// Static fragments composed by adminHtml at their original positions.
// Uses the existing Admin script scope: api/esc/showToast, navigation and Product/
// Appearance/Section draft adapters. No extra listener registration or state copy.
export const sharedMediaPanelHtml = `  <div id="websiteMediaPanel" class="hidden">
    <div class="media-library-layout">
      <section class="panel media-library-upload">
        <div class="chart-head"><div><h2>Add image</h2><small class="muted">Upload once, then reuse it across Products, Homepage and Sections.</small></div></div>
        <div class="editor-field" style="margin-top:12px"><label>Image</label><input id="sharedMediaFile" type="file" accept="image/jpeg,image/png,image/webp"></div>
        <div class="editor-field" style="margin-top:10px"><label>Title · optional</label><input class="field" id="sharedMediaTitle" maxlength="160" placeholder="e.g. Christmas shop window"></div>
        <div class="editor-field" style="margin-top:10px"><label>Alt text</label><input class="field" id="sharedMediaAlt" maxlength="240" placeholder="Describe what is in the image"></div>
        <details class="advanced-details" style="margin-top:12px"><summary>Organise in library · optional</summary><div class="advanced-body"><div class="editor-field"><label for="sharedMediaContext">Library category</label><select class="field" id="sharedMediaContext"><option value="GENERAL">General</option><option value="PRODUCT">Products</option><option value="HOMEPAGE">Homepage</option><option value="SECTION">Sections</option><option value="THEME">Themes</option></select></div><p class="media-upload-note">This helps you filter images later. It does not place the image on the website.</p></div></details>
        <div class="media-upload-note" style="margin-top:9px">JPEG, PNG or WebP · maximum 8 MB. Uploads are stored safely and ready to reuse.</div>
        <button class="btn" id="sharedMediaUpload" type="button" style="margin-top:12px;width:100%">Add to Image Library</button>
      </section>
      <section class="panel" style="padding:16px;min-width:0">
        <div class="chart-head"><div><h2>Image Library</h2><small class="muted">Browse and reuse uploads. Archive hides an image from future choices without breaking published or historical pages.</small></div></div>
        <div class="media-library-toolbar">
          <input class="field" id="sharedMediaSearch" placeholder="Search images…" autocomplete="off">
          <select class="field" id="sharedMediaFilter" aria-label="Library category"><option value="">All categories</option><option value="PRODUCT">Products</option><option value="HOMEPAGE">Homepage</option><option value="SECTION">Sections</option><option value="THEME">Themes</option><option value="GENERAL">General</option></select>
          <label class="catalogue-switch"><input type="checkbox" id="sharedMediaShowArchived"> Show archived</label>
        </div>
        <div class="media-library-grid" id="sharedMediaGrid"><div class="empty">Open Image Library to load images.</div></div>
      </section>
    </div>
    <dialog class="media-usage-dialog" id="sharedMediaUsage" aria-label="Image usage"><div id="sharedMediaUsageBody"></div><form method="dialog"><button class="btn secondary" type="submit">Close</button></form></dialog>
  </div>
`;

export const sharedMediaStateScript = `sharedMediaAssets=[],sharedMediaLoaded=false,sharedMediaSearchTimer=null,`;

export const sharedMediaScript = `function sharedMediaContextLabel(v){return v==='PRODUCT'?'Products':v==='HOMEPAGE'?'Homepage':v==='SECTION'?'Sections':v==='THEME'?'Themes':'General'}
function renderSharedMedia(){var grid=document.getElementById('sharedMediaGrid');if(!grid)return;if(!sharedMediaAssets.length){grid.innerHTML='<div class="empty">No matching images yet. Upload the first image on the left.</div>';return}grid.innerHTML=sharedMediaAssets.map(function(a){var archive=a.status==='ARCHIVED'?'<button class="btn secondary" data-shared-media-restore="'+esc(a.id)+'">Restore</button><button class="btn danger" data-shared-media-delete="'+esc(a.id)+'">Delete object</button>':'<button class="btn secondary" data-shared-media-archive="'+esc(a.id)+'">Archive</button>';return '<article class="media-library-card '+(a.status==='ARCHIVED'?'archived':'')+'"><img loading="lazy" src="'+esc(a.publicUrl)+'" alt="'+esc(a.altText||'')+'"><div class="media-library-card-body"><div><div class="media-library-card-title">'+esc(a.title||'Untitled image')+'</div><div class="media-library-card-meta">'+esc(sharedMediaContextLabel(a.context))+' · '+esc(a.status==='ARCHIVED'?'Archived':'Active')+' · '+(Number(a.currentUsageCount||0)>0?esc(a.currentUsageCount)+' current place'+(Number(a.currentUsageCount)===1?'':'s'):Number(a.usageCount||0)>0?'Retained by saved content':'Unused')+'</div></div><div class="media-library-card-meta">'+esc(a.altText||'No alt text yet')+'</div><div class="media-library-actions">'+'<button class="btn secondary" data-shared-media-edit="'+esc(a.id)+'">Edit details</button><button class="btn secondary" data-shared-media-usage="'+esc(a.id)+'">View usage</button>'+archive+'</div></div></article>'}).join('');grid.querySelectorAll('[data-shared-media-edit]').forEach(function(b){b.onclick=function(){editSharedMediaAsset(b.getAttribute('data-shared-media-edit'))}});grid.querySelectorAll('[data-shared-media-usage]').forEach(function(b){b.onclick=function(){viewSharedMediaUsage(b.getAttribute('data-shared-media-usage'))}});grid.querySelectorAll('[data-shared-media-archive]').forEach(function(b){b.onclick=function(){archiveSharedMediaAsset(b.getAttribute('data-shared-media-archive'))}});grid.querySelectorAll('[data-shared-media-restore]').forEach(function(b){b.onclick=function(){restoreSharedMediaAsset(b.getAttribute('data-shared-media-restore'))}});grid.querySelectorAll('[data-shared-media-delete]').forEach(function(b){b.onclick=function(){deleteSharedMediaAsset(b.getAttribute('data-shared-media-delete'))}})}
async function viewSharedMediaUsage(id){var panel=document.getElementById('sharedMediaUsage'),body=document.getElementById('sharedMediaUsageBody');if(!panel||!body)return;body.innerHTML='<div class="empty">Loading usage…</div>';panel.showModal();try{var d=await api('/admin/api/media/'+encodeURIComponent(id)+'/usage'),places=d.places||[];if(!panel.open)return;body.innerHTML='<h2>'+esc(d.asset.title||'Untitled image')+'</h2>'+(places.length?'<p>Used in '+places.length+' current place'+(places.length===1?'':'s')+'.</p><ul class="media-usage-list">'+places.map(function(place){return '<li><strong>'+esc(place.label)+'</strong><span>'+esc(place.type==='PRODUCT'?'Product':place.type==='SECTION'?'Section':'Homepage')+' · '+esc(place.published&&place.draft?'Published and draft':place.published?'Published':'Draft only')+'</span></li>'}).join('')+'</ul>':'<p>'+(Number(d.asset.usageCount||0)>0?'Not used in current content. Saved history or another protected reference keeps this image available.':'Unused. This image is not placed in current content or saved history.')+'</p>')}catch(e){body.innerHTML='<p>Usage could not be loaded. Try again.</p>';showToast(e.message,true)}}
function sharedMediaListUrl(q,context,archived){return '/admin/api/media?includeArchived='+(archived?'1':'0')+'&context='+encodeURIComponent(context||'')+'&q='+encodeURIComponent(q||'')}
async function loadSharedMedia(force){if(sharedMediaLoaded&&!force){renderSharedMedia();return}try{var q=(document.getElementById('sharedMediaSearch')&&document.getElementById('sharedMediaSearch').value||'').trim(),context=document.getElementById('sharedMediaFilter')&&document.getElementById('sharedMediaFilter').value||'',archived=document.getElementById('sharedMediaShowArchived')&&document.getElementById('sharedMediaShowArchived').checked;var d=await api(sharedMediaListUrl(q,context,archived));sharedMediaAssets=d.assets||[];sharedMediaLoaded=true;renderSharedMedia()}catch(e){showToast(e.message,true)}}
async function attachExistingProductImage(asset,results){if(!productCurrent)return;var buttons=results.querySelectorAll('button');buttons.forEach(function(button){button.disabled=true});try{var d=await api('/admin/api/products/'+encodeURIComponent(productCurrent.id)+'/media/from-library',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({expectedVersion:productCurrent.version,assetId:asset.id})});await refreshMediaProduct(d,'Existing image added to Product draft. Publish the draft when ready.')}catch(e){showToast(e.message,true);buttons.forEach(function(button){button.disabled=false})}}
async function loadInlineImageChoices(kind){var hero=kind==='hero',product=kind==='product',prefix=product?'productMedia':hero?'appearanceHero':'structureImage',panel=document.getElementById(prefix+'Picker'),search=document.getElementById(prefix+'Search'),results=document.getElementById(prefix+'Results'),attr=product?'data-product-media-choice':hero?'data-appearance-image-choice':'data-structure-image-choice';if(!panel||!search||!results||panel.classList.contains('hidden'))return;var q=search.value.trim();results.innerHTML='<div class="empty">Loading images…</div>';try{var d=await api(sharedMediaListUrl(q,'',false));if(!panel.isConnected||panel.classList.contains('hidden')||search.value.trim()!==q)return;var assets=(d.assets||[]).filter(function(a){return a.status==='ACTIVE'}).slice(0,24);if(!assets.length){results.innerHTML='<div class="empty">'+(q?'No matching images. Try another search.':'No images in the library yet. Upload an image to use it here.')+'</div>';return}results.innerHTML=assets.map(function(a){return '<button class="structure-image-choice" type="button" '+attr+'="'+esc(a.id)+'"><img loading="lazy" src="'+esc(a.publicUrl)+'" alt=""><span>'+esc(a.title||a.altText||'Untitled image')+'</span></button>'}).join('');results.querySelectorAll('['+attr+']').forEach(function(button){button.onclick=function(){var asset=assets.find(function(a){return a.id===button.getAttribute(attr)});if(!asset)return;if(product){attachExistingProductImage(asset,results);return}document.getElementById(hero?'appearanceHeroImage':'structureImageUrl').value=asset.publicUrl;setAdminImagePreview(document.getElementById(prefix+'Preview'),asset.publicUrl,asset.altText||(hero?'Homepage hero':'Website section'));panel.classList.add('hidden');showToast(hero?'Hero image selected. Save or Preview the Appearance draft when ready.':'Image selected. Save changes, then Publish this section.')}})}catch(e){if(panel.isConnected)results.innerHTML='<div class="empty">Images could not be loaded. Try again.</div>';showToast(e.message,true)}}
function toggleInlineImageChoices(kind){var prefix=kind==='product'?'productMedia':kind==='hero'?'appearanceHero':'structureImage',panel=document.getElementById(prefix+'Picker');if(!panel)return;panel.classList.toggle('hidden');if(!panel.classList.contains('hidden')){document.getElementById(prefix+'Search').focus();loadInlineImageChoices(kind)}}
function loadStructureImageChoices(){return loadInlineImageChoices('structure')}
function toggleStructureImageChoices(){toggleInlineImageChoices('structure')}
function loadHeroImageChoices(){return loadInlineImageChoices('hero')}
function toggleHeroImageChoices(){toggleInlineImageChoices('hero')}
function toggleProductImageChoices(){toggleInlineImageChoices('product')}
function storefrontImageUrl(url){return typeof url==='string'&&url.charAt(0)==='/'&&url.charAt(1)!=='/'&&url.slice(0,7)!=='/media/'?'https://theblacksheepshop.co.uk'+url:url}
function adminImagePreviewHtml(url,alt){return url?'<img src="'+esc(storefrontImageUrl(url))+'" alt="'+esc(alt||'')+'">':'<span>No image selected</span>'}
function setAdminImagePreview(root,url,alt){if(root)root.innerHTML=adminImagePreviewHtml(url,alt)}
function chooseSharedMediaDuplicate(asset){return new Promise(function(resolve){var dialog=document.createElement('dialog');dialog.className='media-usage-dialog media-duplicate-dialog';dialog.setAttribute('aria-label','Image already exists');dialog.innerHTML='<h2>This image already exists</h2><div class="media-duplicate-preview"><img src="'+esc(asset.publicUrl)+'" alt=""><p>'+esc(asset.title||'This image is in your Image Library')+'</p></div><p>Use the existing image, or keep a separate copy with its own history.</p><div class="media-duplicate-actions"><button class="btn" type="button" value="reuse">Reuse existing</button><button class="btn secondary" type="button" value="separate">Upload separately</button><button class="btn secondary" type="button" value="cancel">Cancel</button></div>';document.body.appendChild(dialog);dialog.querySelectorAll('button').forEach(function(button){button.onclick=function(){dialog.close(button.value)}});dialog.onclose=function(){var decision=dialog.returnValue||'cancel';dialog.remove();resolve(decision)};dialog.showModal()})}
async function uploadSharedImageFile(file,options){if(!file)throw new Error('Choose an image first.');var opts=options||{},form=new FormData();form.append('file',file);form.append('title',opts.title||'');form.append('altText',opts.altText||'');form.append('context',opts.context||'GENERAL');var r=await fetch('/admin/api/media',{method:'POST',body:form}),d=await r.json().catch(function(){return {}});if(r.status===409&&d.error&&d.error.code==='shared_media_duplicate'&&d.existingAsset){var decision=await chooseSharedMediaDuplicate(d.existingAsset);if(decision==='reuse')return d.existingAsset;if(decision==='cancel')throw new Error('shared_media_upload_cancelled');form.set('allowDuplicate','1');r=await fetch('/admin/api/media',{method:'POST',body:form});d=await r.json().catch(function(){return {}})}if(!r.ok)throw new Error(d&&d.error&&(d.error.message||d.error.code)||'Upload failed');if(!d.asset||!d.asset.publicUrl)throw new Error('Image Library upload did not return an image.');sharedMediaLoaded=false;return d.asset}
async function uploadAppearanceHeroImage(file){var controls=['appearanceSaveDraft','appearancePreview','appearancePublish','appearanceHeroClear','appearanceHeroChooseMedia','appearanceHeroUploadButton'].map(function(id){return document.getElementById(id)}),disabled=controls.map(function(button){return button&&button.disabled});controls.forEach(function(button){if(button)button.disabled=true});try{var a=await uploadSharedImageFile(file,{title:'Homepage hero',altText:'The Black Sheep Shop homepage hero',context:'HOMEPAGE'});document.getElementById('appearanceHeroImage').value=a.publicUrl;setAdminImagePreview(document.getElementById('appearanceHeroPreview'),a.publicUrl,a.altText||'Homepage hero');showToast('Hero image selected. Save or Preview when ready.')}catch(e){if(e.message!=='shared_media_upload_cancelled')showToast(e.message,true)}finally{controls.forEach(function(button,index){if(button)button.disabled=disabled[index]})}}
async function uploadStructureImage(file){var name=document.getElementById('structureName')&&document.getElementById('structureName').value.trim();if(!name){showToast('Enter the section name first so the image can be named automatically.',true);return}var save=document.getElementById('saveStructureNode'),upload=document.getElementById('structureImageUploadButton'),clear=document.getElementById('structureImageClear'),oldLabel=upload&&upload.textContent;if(save)save.disabled=true;if(clear)clear.disabled=true;if(upload){upload.disabled=true;upload.textContent='Uploading image…'}try{var a=await uploadSharedImageFile(file,{title:name+' — section image',altText:name,context:'SECTION'}),input=document.getElementById('structureImageUrl');if(input)input.value=a.publicUrl;setAdminImagePreview(document.getElementById('structureImagePreview'),a.publicUrl,a.altText||name);showToast('Image selected. Save changes, then Publish this section.')}catch(e){if(e.message!=='shared_media_upload_cancelled')showToast(e.message,true)}finally{if(save)save.disabled=false;if(clear)clear.disabled=false;if(upload){upload.disabled=false;upload.textContent=oldLabel}}}
async function uploadSharedMedia(){var input=document.getElementById('sharedMediaFile'),file=input&&input.files&&input.files[0],button=document.getElementById('sharedMediaUpload');if(!file){showToast('Choose an image first.',true);return}button.disabled=true;button.textContent='Uploading…';try{await uploadSharedImageFile(file,{title:document.getElementById('sharedMediaTitle').value||'',altText:document.getElementById('sharedMediaAlt').value||'',context:document.getElementById('sharedMediaContext').value||'GENERAL'});input.value='';document.getElementById('sharedMediaTitle').value='';document.getElementById('sharedMediaAlt').value='';await loadSharedMedia(true);showToast('Image ready in the library.')}catch(e){if(e.message!=='shared_media_upload_cancelled')showToast(e.message,true)}finally{button.disabled=false;button.textContent='Add to Image Library'}}
async function editSharedMediaAsset(id){var a=sharedMediaAssets.find(function(x){return x.id===id});if(!a)return;var title=prompt('Image title',a.title||'');if(title===null)return;var alt=prompt('Alt text',a.altText||'');if(alt===null)return;try{await api('/admin/api/media/'+encodeURIComponent(id),{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({title:title,altText:alt,context:a.context})});sharedMediaLoaded=false;await loadSharedMedia(true);showToast('Image details updated.')}catch(e){showToast(e.message,true)}}
async function archiveSharedMediaAsset(id){if(!confirm('Archive this image? Existing published and historical pages keep working, but it will be hidden from future choices.'))return;try{await api('/admin/api/media/'+encodeURIComponent(id)+'/archive',{method:'POST'});sharedMediaLoaded=false;await loadSharedMedia(true);showToast('Image archived safely.')}catch(e){showToast(e.message,true)}}
async function restoreSharedMediaAsset(id){try{await api('/admin/api/media/'+encodeURIComponent(id)+'/restore',{method:'POST'});sharedMediaLoaded=false;await loadSharedMedia(true);showToast('Image restored to the Media Library.')}catch(e){showToast(e.message,true)}}
async function deleteSharedMediaAsset(id){if(!confirm('Permanently remove the R2 object? This is allowed only when no Product or website history references it.'))return;try{await api('/admin/api/media/'+encodeURIComponent(id),{method:'DELETE'});sharedMediaLoaded=false;await loadSharedMedia(true);showToast('Unused media object removed.')}catch(e){showToast(e.message,true)}}
`;

export const sharedMediaBindingsScript = `document.getElementById('sharedMediaUpload').onclick=uploadSharedMedia;document.getElementById('sharedMediaSearch').oninput=function(){clearTimeout(sharedMediaSearchTimer);sharedMediaSearchTimer=setTimeout(function(){sharedMediaLoaded=false;loadSharedMedia(true)},180)};document.getElementById('sharedMediaFilter').onchange=function(){sharedMediaLoaded=false;loadSharedMedia(true)};document.getElementById('sharedMediaShowArchived').onchange=function(){sharedMediaLoaded=false;loadSharedMedia(true)};`;
