// Static fragments composed by adminHtml at their original positions.
// Uses the existing Admin script scope: api/esc/showToast, navigation and Product/
// Appearance/Section draft adapters. No extra listener registration or state copy.
export const sharedMediaPanelHtml = `  <div id="websiteMediaPanel" class="hidden">
    <div class="media-picker-banner hidden" id="mediaPickerBanner"></div>
    <div class="media-library-layout">
      <section class="panel media-library-upload">
        <div class="chart-head"><div><h2>Add image</h2><small class="muted">Upload once, then reuse it across Products, Homepage and Sections.</small></div></div>
        <div class="editor-field" style="margin-top:12px"><label>Image</label><input id="sharedMediaFile" type="file" accept="image/jpeg,image/png,image/webp"></div>
        <div class="editor-field" style="margin-top:10px"><label>Title · optional</label><input class="field" id="sharedMediaTitle" maxlength="160" placeholder="e.g. Christmas shop window"></div>
        <div class="editor-field" style="margin-top:10px"><label>Alt text</label><input class="field" id="sharedMediaAlt" maxlength="240" placeholder="Describe what is in the image"></div>
        <div class="editor-field" style="margin-top:10px"><label>Use</label><select class="field" id="sharedMediaContext"><option value="GENERAL">General</option><option value="PRODUCT">Products</option><option value="HOMEPAGE">Homepage</option><option value="SECTION">Sections</option><option value="THEME">Themes</option></select></div>
        <div class="media-upload-note" style="margin-top:9px">JPEG, PNG or WebP · maximum 8 MB. The file stays private in R2 and is served through the shop domain.</div>
        <button class="btn" id="sharedMediaUpload" type="button" style="margin-top:12px;width:100%">Upload to Media Library</button>
      </section>
      <section class="panel" style="padding:16px;min-width:0">
        <div class="chart-head"><div><h2>Media Library</h2><small class="muted">Archive hides an image from future choices without breaking published or historical pages.</small></div></div>
        <div class="media-library-toolbar">
          <input class="field" id="sharedMediaSearch" placeholder="Search images…" autocomplete="off">
          <select class="field" id="sharedMediaFilter"><option value="">All uses</option><option value="PRODUCT">Products</option><option value="HOMEPAGE">Homepage</option><option value="SECTION">Sections</option><option value="THEME">Themes</option><option value="GENERAL">General</option></select>
          <label class="catalogue-switch"><input type="checkbox" id="sharedMediaShowArchived"> Show archived</label>
        </div>
        <div class="media-library-grid" id="sharedMediaGrid"><div class="empty">Open Media to load images.</div></div>
      </section>
    </div>
  </div>
`;

export const sharedMediaStateScript = `sharedMediaAssets=[],sharedMediaLoaded=false,sharedMediaSearchTimer=null,mediaPickerTarget=null,`;

export const sharedMediaScript = `function sharedMediaContextLabel(v){return v==='PRODUCT'?'Products':v==='HOMEPAGE'?'Homepage':v==='SECTION'?'Sections':v==='THEME'?'Themes':'General'}
function sharedMediaPickerLabel(){if(!mediaPickerTarget)return '';if(mediaPickerTarget.type==='hero')return 'Choose an image for the Homepage Hero. Selecting an image fills the private Appearance draft only.';if(mediaPickerTarget.type==='section')return 'Choose an image for this website section. Selecting an image fills the private Appearance draft only.';if(mediaPickerTarget.type==='product')return 'Choose an existing image for this Product gallery. It will be attached to the Product draft without uploading a duplicate.';return ''}
function renderSharedMedia(){var grid=document.getElementById('sharedMediaGrid'),banner=document.getElementById('mediaPickerBanner');if(!grid)return;if(banner){var label=sharedMediaPickerLabel();banner.textContent=label;banner.classList.toggle('hidden',!label)}if(!sharedMediaAssets.length){grid.innerHTML='<div class="empty">No matching images yet. Upload the first image on the left.</div>';return}grid.innerHTML=sharedMediaAssets.map(function(a){var pick=mediaPickerTarget&&a.status==='ACTIVE'?'<button class="btn" data-shared-media-use="'+esc(a.id)+'">Use this image</button>':'';var archive=a.status==='ARCHIVED'?'<button class="btn secondary" data-shared-media-restore="'+esc(a.id)+'">Restore</button><button class="btn danger" data-shared-media-delete="'+esc(a.id)+'">Delete object</button>':'<button class="btn secondary" data-shared-media-archive="'+esc(a.id)+'">Archive</button>';return '<article class="media-library-card '+(a.status==='ARCHIVED'?'archived':'')+'"><img loading="lazy" src="'+esc(a.publicUrl)+'" alt="'+esc(a.altText||'')+'"><div class="media-library-card-body"><div><div class="media-library-card-title">'+esc(a.title||'Untitled image')+'</div><div class="media-library-card-meta">'+esc(sharedMediaContextLabel(a.context))+' · '+esc(a.status==='ARCHIVED'?'Archived':'Active')+' · '+esc(a.usageCount||0)+' tracked use'+(Number(a.usageCount||0)===1?'':'s')+'</div></div><div class="media-library-card-meta">'+esc(a.altText||'No alt text yet')+'</div><div class="media-library-actions">'+pick+'<button class="btn secondary" data-shared-media-edit="'+esc(a.id)+'">Edit details</button>'+archive+'</div></div></article>'}).join('');grid.querySelectorAll('[data-shared-media-use]').forEach(function(b){b.onclick=function(){useSharedMediaAsset(b.getAttribute('data-shared-media-use'))}});grid.querySelectorAll('[data-shared-media-edit]').forEach(function(b){b.onclick=function(){editSharedMediaAsset(b.getAttribute('data-shared-media-edit'))}});grid.querySelectorAll('[data-shared-media-archive]').forEach(function(b){b.onclick=function(){archiveSharedMediaAsset(b.getAttribute('data-shared-media-archive'))}});grid.querySelectorAll('[data-shared-media-restore]').forEach(function(b){b.onclick=function(){restoreSharedMediaAsset(b.getAttribute('data-shared-media-restore'))}});grid.querySelectorAll('[data-shared-media-delete]').forEach(function(b){b.onclick=function(){deleteSharedMediaAsset(b.getAttribute('data-shared-media-delete'))}})}
async function loadSharedMedia(force){if(sharedMediaLoaded&&!force){renderSharedMedia();return}try{var q=(document.getElementById('sharedMediaSearch')&&document.getElementById('sharedMediaSearch').value||'').trim(),context=document.getElementById('sharedMediaFilter')&&document.getElementById('sharedMediaFilter').value||'',archived=document.getElementById('sharedMediaShowArchived')&&document.getElementById('sharedMediaShowArchived').checked;var d=await api('/admin/api/media?includeArchived='+(archived?'1':'0')+'&context='+encodeURIComponent(context)+'&q='+encodeURIComponent(q));sharedMediaAssets=d.assets||[];sharedMediaLoaded=true;renderSharedMedia()}catch(e){showToast(e.message,true)}}
function storefrontImageUrl(url){return typeof url==='string'&&url.charAt(0)==='/'&&url.charAt(1)!=='/'&&url.slice(0,7)!=='/media/'?'https://theblacksheepshop.co.uk'+url:url}
function adminImagePreviewHtml(url,alt){return url?'<img src="'+esc(storefrontImageUrl(url))+'" alt="'+esc(alt||'')+'">':'<span>No image selected</span>'}
function setAdminImagePreview(root,url,alt){if(root)root.innerHTML=adminImagePreviewHtml(url,alt)}
async function uploadSharedImageFile(file,options){if(!file)throw new Error('Choose an image first.');var opts=options||{},form=new FormData();form.append('file',file);form.append('title',opts.title||'');form.append('altText',opts.altText||'');form.append('context',opts.context||'GENERAL');var r=await fetch('/admin/api/media',{method:'POST',body:form}),d=await r.json().catch(function(){return {}});if(!r.ok)throw new Error(d&&d.error&&(d.error.message||d.error.code)||'Upload failed');if(!d.asset||!d.asset.publicUrl)throw new Error('Media Library upload did not return an image.');sharedMediaLoaded=false;return d.asset}
async function uploadAppearanceHeroImage(file){try{var a=await uploadSharedImageFile(file,{title:'Homepage hero',altText:'The Black Sheep Shop homepage hero',context:'HOMEPAGE'});document.getElementById('appearanceHeroImage').value=a.publicUrl;setAdminImagePreview(document.getElementById('appearanceHeroPreview'),a.publicUrl,a.altText||'Homepage hero');showToast('Hero image uploaded and selected. Save or Preview when ready.')}catch(e){showToast(e.message,true)}}
async function uploadAppearanceSectionImage(key,file){try{var node=storefrontNodes.find(function(n){return (n.stableKey||n.slug||n.id)===key}),name=node&&node.name||'Website section',a=await uploadSharedImageFile(file,{title:name+' — section image',altText:name,context:'SECTION'}),input=document.querySelector('[data-appearance-section-image="'+CSS.escape(key)+'"]'),preview=document.querySelector('[data-appearance-section-preview="'+CSS.escape(key)+'"]');if(input)input.value=a.publicUrl;setAdminImagePreview(preview,a.publicUrl,a.altText||name);showToast('Section image uploaded and selected. Save or Preview when ready.')}catch(e){showToast(e.message,true)}}
async function uploadStructureImage(file){var name=document.getElementById('structureName')&&document.getElementById('structureName').value.trim();if(!name){showToast('Enter the section name first so the image can be named automatically.',true);return}try{var a=await uploadSharedImageFile(file,{title:name+' — section image',altText:name,context:'SECTION'}),input=document.getElementById('structureImageUrl');if(input)input.value=a.publicUrl;setAdminImagePreview(document.getElementById('structureImagePreview'),a.publicUrl,a.altText||name);showToast('Section image uploaded and attached to this draft.')}catch(e){showToast(e.message,true)}}
async function uploadSharedMedia(){var input=document.getElementById('sharedMediaFile'),file=input&&input.files&&input.files[0],button=document.getElementById('sharedMediaUpload');if(!file){showToast('Choose an image first.',true);return}button.disabled=true;button.textContent='Uploading…';try{await uploadSharedImageFile(file,{title:document.getElementById('sharedMediaTitle').value||'',altText:document.getElementById('sharedMediaAlt').value||'',context:document.getElementById('sharedMediaContext').value||'GENERAL'});input.value='';document.getElementById('sharedMediaTitle').value='';document.getElementById('sharedMediaAlt').value='';await loadSharedMedia(true);showToast('Image uploaded once and ready to reuse.')}catch(e){showToast(e.message,true)}finally{button.disabled=false;button.textContent='Upload to Media Library'}}
async function editSharedMediaAsset(id){var a=sharedMediaAssets.find(function(x){return x.id===id});if(!a)return;var title=prompt('Image title',a.title||'');if(title===null)return;var alt=prompt('Alt text',a.altText||'');if(alt===null)return;try{await api('/admin/api/media/'+encodeURIComponent(id),{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({title:title,altText:alt,context:a.context})});sharedMediaLoaded=false;await loadSharedMedia(true);showToast('Image details updated.')}catch(e){showToast(e.message,true)}}
async function archiveSharedMediaAsset(id){if(!confirm('Archive this image? Existing published and historical pages keep working, but it will be hidden from future choices.'))return;try{await api('/admin/api/media/'+encodeURIComponent(id)+'/archive',{method:'POST'});sharedMediaLoaded=false;await loadSharedMedia(true);showToast('Image archived safely.')}catch(e){showToast(e.message,true)}}
async function restoreSharedMediaAsset(id){try{await api('/admin/api/media/'+encodeURIComponent(id)+'/restore',{method:'POST'});sharedMediaLoaded=false;await loadSharedMedia(true);showToast('Image restored to the Media Library.')}catch(e){showToast(e.message,true)}}
async function deleteSharedMediaAsset(id){if(!confirm('Permanently remove the R2 object? This is allowed only when no Product or website history references it.'))return;try{await api('/admin/api/media/'+encodeURIComponent(id),{method:'DELETE'});sharedMediaLoaded=false;await loadSharedMedia(true);showToast('Unused media object removed.')}catch(e){showToast(e.message,true)}}
function openSharedMediaPicker(type,key){mediaPickerTarget={type:type,key:key||null};setView('website');setWebsiteTab('media');sharedMediaLoaded=false;loadSharedMedia(true)}
async function useSharedMediaAsset(id){var a=sharedMediaAssets.find(function(x){return x.id===id}),target=mediaPickerTarget;if(!a||!target)return;if(target.type==='hero'){mediaPickerTarget=null;setWebsiteTab('appearance');document.getElementById('appearanceHeroImage').value=a.publicUrl;setAdminImagePreview(document.getElementById('appearanceHeroPreview'),a.publicUrl,a.altText||'Homepage hero');showToast('Hero image selected. Save or Preview the Appearance draft when ready.');return}if(target.type==='section'){mediaPickerTarget=null;setWebsiteTab('appearance');var input=document.querySelector('[data-appearance-section-image="'+CSS.escape(target.key)+'"]'),preview=document.querySelector('[data-appearance-section-preview="'+CSS.escape(target.key)+'"]');if(input)input.value=a.publicUrl;setAdminImagePreview(preview,a.publicUrl,a.altText||'Section image');showToast('Section image selected. Save or Preview the Appearance draft when ready.');return}if(target.type==='product'&&productCurrent){try{var d=await api('/admin/api/products/'+encodeURIComponent(productCurrent.id)+'/media/from-library',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({expectedVersion:productCurrent.version,assetId:a.id})});mediaPickerTarget=null;productCurrent=d.product;productsLoaded=false;setView('products');renderProductDetail(productCurrent);openResponsiveProductDetail();openProductMediaManager();showToast('Existing Media Library image added to the Product draft.')}catch(e){showToast(e.message,true)}}}
`;

export const sharedMediaBindingsScript = `document.getElementById('sharedMediaUpload').onclick=uploadSharedMedia;document.getElementById('sharedMediaSearch').oninput=function(){clearTimeout(sharedMediaSearchTimer);sharedMediaSearchTimer=setTimeout(function(){sharedMediaLoaded=false;loadSharedMedia(true)},180)};document.getElementById('sharedMediaFilter').onchange=function(){sharedMediaLoaded=false;loadSharedMedia(true)};document.getElementById('sharedMediaShowArchived').onchange=function(){sharedMediaLoaded=false;loadSharedMedia(true)};`;
